version: '3.8'

services:
  web:
    build: .
    container_name: weather_api_wrapper
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:3000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:
