# Generated by Django 4.0.6 on 2024-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_defined_id', models.CharField(help_text='User defined ID for this weather data', max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True, help_text='Time when the request was made')),
                ('city_id', models.IntegerField(help_text='City ID from OpenWeatherMap API')),
                ('temperature_celsius', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity in percentage')),
            ],
        ),
    ]
